repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
    additional_dependencies: ['future-fstrings==1.0.0']
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.16'
    hooks:
    -   id: isort