name: incense
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - tensorflow
  - scikit-learn
  - mongodb
  - seaborn
  - pip:
    - git+https://github.com/IDSIA/sacred.git
    - incense
