version: '3.3'

services:

  mongo:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
    env_file: .env

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["-m", "mongo:27017:$MONGO_DATABASE"]
    ports:
      - 127.0.0.1:9000:9000
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo


